import { DELIVERY_STATUS } from "./constants.js";

export const deliveriesDB = [
  {
    id: 1001,
    order_number: "ORD-1001",
    customer_name: "Ahmed Ali",
    phone: "55512345",
    address: "Salmiya, Block 4, Street 12",
    amount_due: 18.75,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1002,
    order_number: "ORD-1002",
    customer_name: "Fatima Al-Zahra",
    phone: "55567890",
    address: "Hawally, Block 2, Street 5, Building 14",
    amount_due: 34.5,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1003,
    order_number: "ORD-1003",
    customer_name: "Mohammad Khaled",
    phone: "55598765",
    address: "Kuwait City, Sharq, Block 1, Tower 3",
    amount_due: 12.0,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1004,
    order_number: "ORD-1004",
    customer_name: "Sara Al-Otaibi",
    phone: "55543210",
    address: "Farwaniya, Block 3, Street 20",
    amount_due: 25.0,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1005,
    order_number: "ORD-1005",
    customer_name: "Abdullah Al-Enezi",
    phone: "55523456",
    address: "Jabriya, Block 7, Street 105",
    amount_due: 8.5,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1006,
    order_number: "ORD-1006",
    customer_name: "Reem Al-Mutawa",
    phone: "55534567",
    address: "Al-Rawda, Block 3, Street 32",
    amount_due: 42.0,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1007,
    order_number: "ORD-1007",
    customer_name: "Yousef Al-Sabah",
    phone: "55545678",
    address: "Mishref, Block 5, Street 1",
    amount_due: 15.25,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1008,
    order_number: "ORD-1008",
    customer_name: "Noura Al-Fadhli",
    phone: "55556789",
    address: "Fahaheel, Block 9, Street 44",
    amount_due: 29.75,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1009,
    order_number: "ORD-1009",
    customer_name: "Bader Al-Hajri",
    phone: "55567812",
    address: "Sabah Al-Salem, Block 1, Street 101",
    amount_due: 19.5,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  },
  {
    id: 1010,
    order_number: "ORD-1010",
    customer_name: "Mariam Al-Kandari",
    phone: "55578923",
    address: "Dasman, Block 2, Arabian Gulf St",
    amount_due: 31.0,
    payment_method: "cash",
    status: DELIVERY_STATUS.PENDING,
    version: 1,
    recipient_name: null,
    failure_reason: null,
    note: null,
    proof_url: null,
    completed_at: null,
    failed_at: null
  }
];

export const idempotencyStore = new Map();
